### ISSUE TITLE
Unable to reproduce on local cluster

### ISSUE THREAD

**Issue by prateeksahu** [cilium/cilium-perf-networking#5]
Hi Team,

I am looking into reproducing the cilium perf results in a local cluster with 2 hosts running ubuntu connected over a switch.
Since I am not using packet server, I was confused over how to create the packet-hosts.ini file.
Lets assume private IP of the 2 hosts to be 10.0.0.1 and 10.0.0.2. My attempt was:
```
[master]
10.0.0.1 ansible_python_interpreter=python3 ansible_user=<username> ansible_sudo_pass=<userpass> node_ip=10.0.0.1 master=knb-0
[nodes]
10.0.0.2 ansible_python_interpreter=python3 ansible_user=<username> ansible_sudo_pass=<userpass> node_ip=10.0.0.2
```
With the above configs I was able to setup a cluster with the 2 hosts without kube-proxy and with cilium in tunnelling mode (v 1.10.7). i.e. I had reached to the first command to run VXLAN benchmark (https://docs.cilium.io/en/latest/operations/performance/benchmark/#tunneling).
Upon running the benchmark, the client pod was not able to reach the netperf server on knb-srv.
Checking the logs, I could find a couple of warnings both on master and node:
```
level=warning msg="Unable to update ipcache map entry on pod add" error="ipcache entry for podIP 10.217.1.18 owned by kvstore or agent" k8sNamespace=default k8sPodName=knb-srv new-hostIP=10.217.1.18 new-podIP=10.217.1.18 new-podIPs="[{10.217.1.18}]" old-hostIP= old-podIP= old-podIPs="[]" subsys=k8s-watcher
```
I would really appreciate any help in trying to debug my setup. let me know what other logs/info is needed.

log on knb-srv:
```
Starting netserver with host 'IN(6)ADDR_ANY' port '12865' and family AF_UNSPEC
```
log on knb-cli:
```
establish control: are you sure there is a netserver listening on 10.217.1.73 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_UNSPEC to 10.217.1.73 port 12865 address family AF_INET
```

Master and node: Ubunut 20.04
Kernel: 5.11 (master) 5.10 (node)

**Comment by prateeksahu** [comment]
I tried out the `direct-routing` mode and that successfully ran the `kubenetbench` benchmark. It seems tunnelling/vxlan setting is causing some issue with pod2pod communication.
Any insights in this regard will be helpful.

**Comment by pchaigno** [comment]
Could you share a Cilium sysdump? Did you check for pakcet drops reported by Cilium? Did you try to trace the failing connection with Cilium and/or tcpdump?

**Comment by pchaigno** [comment]
It looks like both nodes can't reach pods on the other node. That traffic should go through the tunnel, so most likely explanation is that the encapsulated traffic is dropped. Maybe you need to open a hole in some firewall to allow the VXLAN traffic through?

**Comment by prateeksahu** [comment]
@pchaigno. Apologies for the delay.
I see that VXLAN port 8472 is open on both the nodes
```
master
sudo netstat -a -n | grep 8472                                                                                                                                                                        12:35:38
udp        0      0 0.0.0.0:8472            0.0.0.0:*

node
sudo netstat -a -n | grep 8472                                                                                                                                     
udp        0      0 0.0.0.0:8472            0.0.0.0:*                          
udp6       0      0 :::8472                 :::*
```
While trying to do a tcpdump, I did notice the 'cilium_vxlan' interface was not up on the master.
master:
```
sudo tcpdump -D                                                                                                                                                                                       12:34:07
1.cilium_net [Up, Running]
2.cilium_host [Up, Running]
3.enp2s0 [Up, Running]
4.flannel.1 [Up, Running]
5.lo [Up, Running, Loopback]
6.any (Pseudo-device that captures on all interfaces) [Up, Running]
7.virbr0 [Up]
8.docker0 [Up]
9.virbr1 [Up]
10.virbr2 [Up]
11.bluetooth-monitor (Bluetooth Linux Monitor) [none]
12.nflog (Linux netfilter log (NFLOG) interface) [none]
13.nfqueue (Linux netfilter queue (NFQUEUE) interface) [none]
14.virbr1-nic [none]
15.virbr2-nic [none]
16.virbr0-nic [none]
17.cilium_vxlan [none]
```

the same is up and running on the worker node
```
sudo tcpdump -D                                                                                                                                                    Thu 02/24 12:35 PM CST
[sudo] password for prateek: 
1.cilium_net [Up, Running]
2.cilium_host [Up, Running]
3.cilium_vxlan [Up, Running]
4.enp5s0 [Up, Running]
5.lo [Up, Running, Loopback]
6.any (Pseudo-device that captures on all interfaces) [Up, Running]
7.enp3s0 [Up]
8.virbr0 [Up]
9.docker0 [Up]
10.bluetooth-monitor (Bluetooth Linux Monitor) [none]
11.nflog (Linux netfilter log (NFLOG) interface) [none]
12.nfqueue (Linux netfilter queue (NFQUEUE) interface) [none]
13.virbr0-nic [none]
```
Could you provide instructions on debugging why the interface is not showing up?

**Comment by pchaigno** [comment]
Did you check the Cilium agents and dmesg on the node for errors?

**Comment by prateeksahu** [comment]
Hey @pchaigno, thanks for all the tips and directions.
There was a rogue process on the master which was hogging up the port on which vxlan was supposed to run. Upon reboot and cleaning up the firewall rules, the experiments ran smoothly.
